AUTH_LOGIN = "auth.login"
AUTH_LOGOUT = "auth.logout"
AUTH_REFRESH_FAILED = "auth.refresh_failed"

WORKSPACE_CREATED = "workspace.created"
WORKSPACE_UPDATED = "workspace.updated"
WORKSPACE_MEMBER_ADDED = "workspace.member_added"
WORKSPACE_MEMBER_ROLE_CHANGED = "workspace.member_role_changed"
WORKSPACE_MEMBER_REMOVED = "workspace.member_removed"

API_KEY_CREATED = "api_key.created"
API_KEY_REVOKED = "api_key.revoked"

DASHBOARD_CREATED = "dashboard.created"
DASHBOARD_UPDATED = "dashboard.updated"
DASHBOARD_DELETED = "dashboard.deleted"
WIDGET_CREATED = "widget.created"
WIDGET_UPDATED = "widget.updated"
WIDGET_DELETED = "widget.deleted"

ALERT_CREATED = "alert.created"
ALERT_UPDATED = "alert.updated"
ALERT_DELETED = "alert.deleted"
ALERT_ENABLED = "alert.enabled"
ALERT_DISABLED = "alert.disabled"
ALERT_MANUAL_EVALUATED = "alert.manual_evaluated"
INCIDENT_OPENED = "incident.opened"
INCIDENT_RESOLVED = "incident.resolved"

NOTIFICATION_CHANNEL_CREATED = "notification_channel.created"
NOTIFICATION_CHANNEL_UPDATED = "notification_channel.updated"
NOTIFICATION_CHANNEL_DELETED = "notification_channel.deleted"
NOTIFICATION_CHANNEL_TESTED = "notification_channel.tested"
ALERT_NOTIFICATION_CHANNELS_UPDATED = "alert.notification_channels_updated"
